### ISSUE TITLE
exception a must be non empty

### ISSUE THREAD

**Issue by kkawtar** [yhenon/keras-frcnn#43] opened 2017-05-28 21:00 UTC
Dear yhenon, I'm getting this exception ( a must be non empty ) after the training is started and it keep showing, what does it mean ?

**Comment by sholsapp** [comment] 2017-05-30 18:30
Duplicate of https://github.com/yhenon/keras-frcnn/issues/42.

**Comment by yhenon** [comment] 2017-05-30 19:49
Indeed.

**Closed by yhenon** 2017-05-30 19:49 UTC
