### ISSUE TITLE
Other models instead of ResNet

### ISSUE THREAD

**Issue by jahdiel** [yhenon/keras-frcnn#65] opened 2017-06-15 15:55 UTC
Hi, @yhenon what would be the correct process if one would like to use another model, instead of ResNet as the base ConvNet in the Faster R-CNN pipeline? I am trying to set it up with VGG-19. Thanks, in advance.

**Comment by yhenon** [comment] 2017-06-21 21:31
duplicate of #56

**Closed by yhenon** 2017-06-21 21:31 UTC
