### ISSUE TITLE
the python function sorted

### ISSUE THREAD

**Issue by wanjinchang** [yhenon/keras-frcnn#21] opened 2017-04-24 06:33 UTC
dear editor,when I run the train_frcnn.py,it raised the error TypeError: unorderable types: dict() < dict() from all_img_data = sorted(all_img_data),can you solved for me? Thank you very much!

**Comment by yhenon** [comment] 2017-04-24 20:14
Try using python2 instead of python 3. This is a duplicate of issue #20 so I'll go ahead and close it. Please reopen if issues remain.

**Closed by yhenon** 2017-04-24 20:14 UTC

**Comment by wanjinchang** [comment] 2017-04-25 01:35
I know,but my environment is bulid on python3.5,the structure of all_img_data = sorted(all_img_data),I cannot understand the effect of this function to all_img_data.Looking forward to your reply,thank you!
