### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by shrishtrived** [yhenon/keras-frcnn#99] opened 2017-07-07 09:22 UTC
How can I use this implementation to visualize the model in tensorboard ?

**Comment by mathetes87** [comment] 2017-07-07 12:46
See issue #78. It can be done, but you would need to access either Tensorflow's classes and methods or Tensorboard's Keras callback directly (see [here](https://groups.google.com/forum/#!topic/keras-users/IS-wBskAg0k) for the later)

**Comment by yhenon** [comment] 2017-07-08 19:52
duplicate of #78 as pointed out by @mathetes87

**Closed by yhenon** 2017-07-08 19:52 UTC
