### ISSUE TITLE
Exception: a must be non-empty 

### ISSUE THREAD

**Issue by Nicolas99-9** [yhenon/keras-frcnn#46] opened 2017-05-31 04:54 UTC
I'm trying to run the code but I have the following error : 
"Exception: a must be non-empty"

I haven't defined the class "bg".
{'bg': 0,
 'lava': 2504,
 'obsidian': 2501,
 'redstone_block': 2503,
 'water': 2516}
Should I create negative samples  ?

**Comment by yhenon** [comment] 2017-05-31 19:17
duplicate of #42

**Closed by yhenon** 2017-05-31 19:17 UTC

**Comment by HuangBo-Terraloupe** [comment] 2017-07-12 15:28
Hello,
I also got the same problem, how to solve this problem？
{'Chimney/Ventilation_Pipe': 51913,
 'Roof_Window': 60841,
 'Rooftop_Area': 80822,
 'Solar_Thermal_Panel': 9077,
 'bg': 0}

**Comment by Nicolas99-9** [comment] 2017-07-14 07:42
It was a problem with the path of the images
also check that the bouding boxes are corrected
