### ISSUE TITLE
Stuck with personnal data

### ISSUE THREAD

**Issue by Timonzimm** [yhenon/keras-frcnn#8] opened 2017-03-14 16:29 UTC
When using `simple_parser.py` and `filepath,x1,y1,x2,y2,class_name` on each line of a file correctly, the train script get stuck at "Starting training, epoch 1/50".

Note that I changed these two lines:
`train_samples_per_epoch = 2000 -> len(train_imgs)`
`nb_val_samples = 500 -> len(val_imgs)`

Do you have any idea why this might occur? Any special format required on the images (no different width height among images or anything else) ?

**Comment by kirk86** [comment] 2017-03-18 21:14
I get the exact same thing on gpu. On cpu the code works fine. There must bet something else. I'm actually thinking is due to some of the arguments in the fit_generator. For instance, the queue or the nb_worker.

**Comment by yhenon** [comment] 2017-03-20 19:51
Hi,
Thanks for the report. Looking through the code, it seems like this can happen if the objects are very different from the size of the anchors. I'm currently refactoring the entire generator procedure which should fix the issue, and bring the results more in line with the faster-RCNN algorithm.

There is no restrictions on image size. Images are resized to have their smallest side have 600 pixels. However, very small objects cannot be detected (the ROI pooling operates on a layer that has a stride of 16 pixels).

I should have an update out during the week.

**Comment by kirk86** [comment] 2017-03-20 22:51
@yhenon thanks a lot for the update

**Comment by pGit1** [comment] 2017-04-21 02:53
@yhenon will this work with images that are 32x32 or 128x128? Also should one use Keras 2.0 or 1.xx verision with this. I personally have not made the leap to 2.0 yet due to all the little annoying syntax changes since I am currently in the middle of some projects.

**Comment by kirk86** [comment] 2017-04-21 21:31
@pGit1 it works with keras 1.x.x on cpu. As for the image sizes I highly doubt it. It uses resnet50 as model so you need images of size no smaller than 197x197.

**Comment by yhenon** [comment] 2017-04-24 20:38
I'm going to go ahead and close this since the issue is old. I've pushed an update that should fix things. It also monitors the performance of both the RPN and the classifier, so you can get an idea of where things fail.

**Closed by yhenon** 2017-04-24 20:38 UTC
